### ISSUE TITLE
Translate tw stuff to english

### ISSUE THREAD

**Issue by undefined-sin** [tnsc4502/mnwvs077#1]
Hi,

The source is promissing! It would be great if you could translate to english comments and variable names that are defined in tw language.

It will make easier to a non mandarim speaker to understand and contribute.

Congratulations and thank you for releasing such a polished source.

Best,

**Comment by tnsc4502** [comment]
I would intro some kind of StringPool into the project to make it more easier to be multi-lang supported. Thanks for your response.

**Comment by tnsc4502** [comment]
Well, I just checked it out, I'm wondering where are those variables with TW names? I couldn't find out and not even remember that I had ever named variables in TW(except some skill constants which are not existed in GMS string files). As for comments in TW lang. I would translate all of them into Eng. as soon as I can.

**Comment by undefined-sin** [comment]
> Well, I just checked it out, I'm wondering where are those variables with TW names? I couldn't find out and not even remember that I had ever named variables in TW(except some skill constants which are automatically generated by tools and if the skill ids are not existed in GMS string, it would be TW name in default). As for comments in TW lang. I would translate all of them into Eng. as soon as I can.

Sorry, I mean the constants, mostly job related!

Thanks
